package com.athome.ebusiness.mybatis.client;

import com.athome.ebusiness.mybatis.domain.ExtProduct;
import com.athome.ebusiness.mybatis.domain.ExtCproductCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExtCproductCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int countByExample(ExtCproductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int deleteByExample(ExtCproductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int deleteByPrimaryKey(String extCproductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int insert(ExtProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int insertSelective(ExtProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    List<ExtProduct> selectByExample(ExtCproductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    ExtProduct selectByPrimaryKey(String extCproductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") ExtProduct record, @Param("example") ExtCproductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int updateByExample(@Param("record") ExtProduct record, @Param("example") ExtCproductCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int updateByPrimaryKeySelective(ExtProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_cproduct_c
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    int updateByPrimaryKey(ExtProduct record);
}