package com.athome.ebusiness.mybatis.client;

import com.athome.ebusiness.mybatis.domain.SysCode;
import com.athome.ebusiness.mybatis.domain.SysCodeBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysCodeBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int countByExample(SysCodeBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int deleteByExample(SysCodeBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int deleteByPrimaryKey(String sysCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int insert(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int insertSelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    List<SysCode> selectByExample(SysCodeBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    SysCode selectByPrimaryKey(String sysCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysCode record, @Param("example") SysCodeBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int updateByExample(@Param("record") SysCode record, @Param("example") SysCodeBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int updateByPrimaryKeySelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_code_b
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    int updateByPrimaryKey(SysCode record);
}