package com.athome.ebusiness.domain;

import java.math.BigDecimal;

public class ContractProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.CONTRACT_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.FACTORY_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String factoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.EXPORT_LIST_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String exportListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.INVOICE_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PRODUCT_NAME
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PRODUCT_NO
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PRODUCT_IMAGE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PRODUCT_DESC
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.LOADING_RATE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String loadingRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PACKING_UNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String packingUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.CNUMBER
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private Integer cnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.OUT_NUMBER
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private Integer outNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.FINISHED
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private Boolean finished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.GROSS_WEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal grossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.NET_WEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal netWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.CSIZE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String csize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.SIZE_LENGTH
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal sizeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.SIZE_WIDTH
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal sizeWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.SIZE_HEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal sizeHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PRODUCT_REQUEST
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String productRequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.FACTORY_NAME
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.AMOUNT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.CUNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String cunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.BOX_NUM
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private Integer boxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.EX_PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal exPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.EX_AMOUNT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal exAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.EX_UNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String exUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.NO_TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal noTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.COST_PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.COST_TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private BigDecimal costTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.ACCESSORIES
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private Boolean accessories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.ORDER_NO
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_product_c.EXTS
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    private String exts;

    
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.CONTRACT_ID
     *
     * @return the value of contract_product_c.CONTRACT_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.CONTRACT_ID
     *
     * @param contractId the value for contract_product_c.CONTRACT_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.FACTORY_ID
     *
     * @return the value of contract_product_c.FACTORY_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.FACTORY_ID
     *
     * @param factoryId the value for contract_product_c.FACTORY_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.EXPORT_LIST_ID
     *
     * @return the value of contract_product_c.EXPORT_LIST_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getExportListId() {
        return exportListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.EXPORT_LIST_ID
     *
     * @param exportListId the value for contract_product_c.EXPORT_LIST_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setExportListId(String exportListId) {
        this.exportListId = exportListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.INVOICE_ID
     *
     * @return the value of contract_product_c.INVOICE_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.INVOICE_ID
     *
     * @param invoiceId the value for contract_product_c.INVOICE_ID
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PRODUCT_NAME
     *
     * @return the value of contract_product_c.PRODUCT_NAME
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PRODUCT_NAME
     *
     * @param productName the value for contract_product_c.PRODUCT_NAME
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PRODUCT_NO
     *
     * @return the value of contract_product_c.PRODUCT_NO
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PRODUCT_NO
     *
     * @param productNo the value for contract_product_c.PRODUCT_NO
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PRODUCT_IMAGE
     *
     * @return the value of contract_product_c.PRODUCT_IMAGE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PRODUCT_IMAGE
     *
     * @param productImage the value for contract_product_c.PRODUCT_IMAGE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PRODUCT_DESC
     *
     * @return the value of contract_product_c.PRODUCT_DESC
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PRODUCT_DESC
     *
     * @param productDesc the value for contract_product_c.PRODUCT_DESC
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.LOADING_RATE
     *
     * @return the value of contract_product_c.LOADING_RATE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getLoadingRate() {
        return loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.LOADING_RATE
     *
     * @param loadingRate the value for contract_product_c.LOADING_RATE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setLoadingRate(String loadingRate) {
        this.loadingRate = loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PACKING_UNIT
     *
     * @return the value of contract_product_c.PACKING_UNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PACKING_UNIT
     *
     * @param packingUnit the value for contract_product_c.PACKING_UNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.CNUMBER
     *
     * @return the value of contract_product_c.CNUMBER
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public Integer getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.CNUMBER
     *
     * @param cnumber the value for contract_product_c.CNUMBER
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setCnumber(Integer cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.OUT_NUMBER
     *
     * @return the value of contract_product_c.OUT_NUMBER
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public Integer getOutNumber() {
        return outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.OUT_NUMBER
     *
     * @param outNumber the value for contract_product_c.OUT_NUMBER
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setOutNumber(Integer outNumber) {
        this.outNumber = outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.FINISHED
     *
     * @return the value of contract_product_c.FINISHED
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public Boolean getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.FINISHED
     *
     * @param finished the value for contract_product_c.FINISHED
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.GROSS_WEIGHT
     *
     * @return the value of contract_product_c.GROSS_WEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.GROSS_WEIGHT
     *
     * @param grossWeight the value for contract_product_c.GROSS_WEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.NET_WEIGHT
     *
     * @return the value of contract_product_c.NET_WEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getNetWeight() {
        return netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.NET_WEIGHT
     *
     * @param netWeight the value for contract_product_c.NET_WEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setNetWeight(BigDecimal netWeight) {
        this.netWeight = netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.CSIZE
     *
     * @return the value of contract_product_c.CSIZE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getCsize() {
        return csize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.CSIZE
     *
     * @param csize the value for contract_product_c.CSIZE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setCsize(String csize) {
        this.csize = csize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.SIZE_LENGTH
     *
     * @return the value of contract_product_c.SIZE_LENGTH
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getSizeLength() {
        return sizeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.SIZE_LENGTH
     *
     * @param sizeLength the value for contract_product_c.SIZE_LENGTH
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setSizeLength(BigDecimal sizeLength) {
        this.sizeLength = sizeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.SIZE_WIDTH
     *
     * @return the value of contract_product_c.SIZE_WIDTH
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getSizeWidth() {
        return sizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.SIZE_WIDTH
     *
     * @param sizeWidth the value for contract_product_c.SIZE_WIDTH
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setSizeWidth(BigDecimal sizeWidth) {
        this.sizeWidth = sizeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.SIZE_HEIGHT
     *
     * @return the value of contract_product_c.SIZE_HEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getSizeHeight() {
        return sizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.SIZE_HEIGHT
     *
     * @param sizeHeight the value for contract_product_c.SIZE_HEIGHT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setSizeHeight(BigDecimal sizeHeight) {
        this.sizeHeight = sizeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PRODUCT_REQUEST
     *
     * @return the value of contract_product_c.PRODUCT_REQUEST
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getProductRequest() {
        return productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PRODUCT_REQUEST
     *
     * @param productRequest the value for contract_product_c.PRODUCT_REQUEST
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setProductRequest(String productRequest) {
        this.productRequest = productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.FACTORY_NAME
     *
     * @return the value of contract_product_c.FACTORY_NAME
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.FACTORY_NAME
     *
     * @param factoryName the value for contract_product_c.FACTORY_NAME
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.PRICE
     *
     * @return the value of contract_product_c.PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.PRICE
     *
     * @param price the value for contract_product_c.PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.AMOUNT
     *
     * @return the value of contract_product_c.AMOUNT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.AMOUNT
     *
     * @param amount the value for contract_product_c.AMOUNT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.CUNIT
     *
     * @return the value of contract_product_c.CUNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getCunit() {
        return cunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.CUNIT
     *
     * @param cunit the value for contract_product_c.CUNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setCunit(String cunit) {
        this.cunit = cunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.BOX_NUM
     *
     * @return the value of contract_product_c.BOX_NUM
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public Integer getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.BOX_NUM
     *
     * @param boxNum the value for contract_product_c.BOX_NUM
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setBoxNum(Integer boxNum) {
        this.boxNum = boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.EX_PRICE
     *
     * @return the value of contract_product_c.EX_PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getExPrice() {
        return exPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.EX_PRICE
     *
     * @param exPrice the value for contract_product_c.EX_PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setExPrice(BigDecimal exPrice) {
        this.exPrice = exPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.EX_AMOUNT
     *
     * @return the value of contract_product_c.EX_AMOUNT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getExAmount() {
        return exAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.EX_AMOUNT
     *
     * @param exAmount the value for contract_product_c.EX_AMOUNT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setExAmount(BigDecimal exAmount) {
        this.exAmount = exAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.EX_UNIT
     *
     * @return the value of contract_product_c.EX_UNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getExUnit() {
        return exUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.EX_UNIT
     *
     * @param exUnit the value for contract_product_c.EX_UNIT
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setExUnit(String exUnit) {
        this.exUnit = exUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.NO_TAX
     *
     * @return the value of contract_product_c.NO_TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getNoTax() {
        return noTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.NO_TAX
     *
     * @param noTax the value for contract_product_c.NO_TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setNoTax(BigDecimal noTax) {
        this.noTax = noTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.TAX
     *
     * @return the value of contract_product_c.TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.TAX
     *
     * @param tax the value for contract_product_c.TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.COST_PRICE
     *
     * @return the value of contract_product_c.COST_PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.COST_PRICE
     *
     * @param costPrice the value for contract_product_c.COST_PRICE
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.COST_TAX
     *
     * @return the value of contract_product_c.COST_TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public BigDecimal getCostTax() {
        return costTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.COST_TAX
     *
     * @param costTax the value for contract_product_c.COST_TAX
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setCostTax(BigDecimal costTax) {
        this.costTax = costTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.ACCESSORIES
     *
     * @return the value of contract_product_c.ACCESSORIES
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public Boolean getAccessories() {
        return accessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.ACCESSORIES
     *
     * @param accessories the value for contract_product_c.ACCESSORIES
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setAccessories(Boolean accessories) {
        this.accessories = accessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.ORDER_NO
     *
     * @return the value of contract_product_c.ORDER_NO
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.ORDER_NO
     *
     * @param orderNo the value for contract_product_c.ORDER_NO
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract_product_c.EXTS
     *
     * @return the value of contract_product_c.EXTS
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public String getExts() {
        return exts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract_product_c.EXTS
     *
     * @param exts the value for contract_product_c.EXTS
     *
     * @mbggenerated Mon May 30 11:12:13 CST 2016
     */
    public void setExts(String exts) {
        this.exts = exts;
    }
}