package com.athome.ebusiness.domain;

public class ExtProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.EXT_CPRODUCT_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.FACTORY_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String factoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String contractProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.CTYPE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Integer ctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PRODUCT_NAME
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PRODUCT_NO
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PRODUCT_IMAGE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PRODUCT_DESC
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.LOADING_RATE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String loadingRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PACKING_UNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String packingUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.CNUMBER
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Integer cnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.OUT_NUMBER
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Integer outNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.FINISHED
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Boolean finished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.GROSS_WEIGHT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double grossWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.NET_WEIGHT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double netWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.SIZE_LENGTH
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double sizeLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.SIZE_WIDTH
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double sizeWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.SIZE_HEIGHT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double sizeHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PRODUCT_REQUEST
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String productRequest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.FACTORY_NAME
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.PRICE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.AMOUNT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.CUNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String cunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.BOX_NUM
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Integer boxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.EX_PRICE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double exPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.EX_UNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private String exUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.NO_TAX
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double noTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.TAX
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.COST_PRICE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.COST_TAX
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Double costTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.ACCESSORIES
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Boolean accessories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_cproduct_c.ORDER_NO
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    private Integer orderNo;


    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.FACTORY_ID
     *
     * @return the value of ext_cproduct_c.FACTORY_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.FACTORY_ID
     *
     * @param factoryId the value for ext_cproduct_c.FACTORY_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.CONTRACT_PRODUCT_ID
     *
     * @return the value of ext_cproduct_c.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getContractProductId() {
        return contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.CONTRACT_PRODUCT_ID
     *
     * @param contractProductId the value for ext_cproduct_c.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setContractProductId(String contractProductId) {
        this.contractProductId = contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.CTYPE
     *
     * @return the value of ext_cproduct_c.CTYPE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.CTYPE
     *
     * @param ctype the value for ext_cproduct_c.CTYPE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.PRODUCT_NAME
     *
     * @return the value of ext_cproduct_c.PRODUCT_NAME
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.PRODUCT_NAME
     *
     * @param productName the value for ext_cproduct_c.PRODUCT_NAME
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.PRODUCT_NO
     *
     * @return the value of ext_cproduct_c.PRODUCT_NO
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.PRODUCT_NO
     *
     * @param productNo the value for ext_cproduct_c.PRODUCT_NO
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.PRODUCT_IMAGE
     *
     * @return the value of ext_cproduct_c.PRODUCT_IMAGE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.PRODUCT_IMAGE
     *
     * @param productImage the value for ext_cproduct_c.PRODUCT_IMAGE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.PRODUCT_DESC
     *
     * @return the value of ext_cproduct_c.PRODUCT_DESC
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.PRODUCT_DESC
     *
     * @param productDesc the value for ext_cproduct_c.PRODUCT_DESC
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.LOADING_RATE
     *
     * @return the value of ext_cproduct_c.LOADING_RATE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getLoadingRate() {
        return loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.LOADING_RATE
     *
     * @param loadingRate the value for ext_cproduct_c.LOADING_RATE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setLoadingRate(String loadingRate) {
        this.loadingRate = loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.PACKING_UNIT
     *
     * @return the value of ext_cproduct_c.PACKING_UNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.PACKING_UNIT
     *
     * @param packingUnit the value for ext_cproduct_c.PACKING_UNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.CNUMBER
     *
     * @return the value of ext_cproduct_c.CNUMBER
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Integer getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.CNUMBER
     *
     * @param cnumber the value for ext_cproduct_c.CNUMBER
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setCnumber(Integer cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.OUT_NUMBER
     *
     * @return the value of ext_cproduct_c.OUT_NUMBER
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Integer getOutNumber() {
        return outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.OUT_NUMBER
     *
     * @param outNumber the value for ext_cproduct_c.OUT_NUMBER
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setOutNumber(Integer outNumber) {
        this.outNumber = outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.FINISHED
     *
     * @return the value of ext_cproduct_c.FINISHED
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Boolean getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.FINISHED
     *
     * @param finished the value for ext_cproduct_c.FINISHED
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.PRODUCT_REQUEST
     *
     * @return the value of ext_cproduct_c.PRODUCT_REQUEST
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getProductRequest() {
        return productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.PRODUCT_REQUEST
     *
     * @param productRequest the value for ext_cproduct_c.PRODUCT_REQUEST
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setProductRequest(String productRequest) {
        this.productRequest = productRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.FACTORY_NAME
     *
     * @return the value of ext_cproduct_c.FACTORY_NAME
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.FACTORY_NAME
     *
     * @param factoryName the value for ext_cproduct_c.FACTORY_NAME
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    
    public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.CUNIT
     *
     * @return the value of ext_cproduct_c.CUNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getCunit() {
        return cunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.CUNIT
     *
     * @param cunit the value for ext_cproduct_c.CUNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setCunit(String cunit) {
        this.cunit = cunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.BOX_NUM
     *
     * @return the value of ext_cproduct_c.BOX_NUM
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Integer getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.BOX_NUM
     *
     * @param boxNum the value for ext_cproduct_c.BOX_NUM
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setBoxNum(Integer boxNum) {
        this.boxNum = boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.EX_PRICE
     *
     * @return the value of ext_cproduct_c.EX_PRICE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.EX_UNIT
     *
     * @return the value of ext_cproduct_c.EX_UNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public String getExUnit() {
        return exUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.EX_UNIT
     *
     * @param exUnit the value for ext_cproduct_c.EX_UNIT
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setExUnit(String exUnit) {
        this.exUnit = exUnit;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.COST_PRICE
     *
     * @return the value of ext_cproduct_c.COST_PRICE
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.ACCESSORIES
     *
     * @return the value of ext_cproduct_c.ACCESSORIES
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Boolean getAccessories() {
        return accessories;
    }

    public Double getGrossWeight() {
		return grossWeight;
	}

	public void setGrossWeight(Double grossWeight) {
		this.grossWeight = grossWeight;
	}

	public Double getNetWeight() {
		return netWeight;
	}

	public void setNetWeight(Double netWeight) {
		this.netWeight = netWeight;
	}

	public Double getSizeLength() {
		return sizeLength;
	}

	public void setSizeLength(Double sizeLength) {
		this.sizeLength = sizeLength;
	}

	public Double getSizeWidth() {
		return sizeWidth;
	}

	public void setSizeWidth(Double sizeWidth) {
		this.sizeWidth = sizeWidth;
	}

	public Double getSizeHeight() {
		return sizeHeight;
	}

	public void setSizeHeight(Double sizeHeight) {
		this.sizeHeight = sizeHeight;
	}

	public Double getExPrice() {
		return exPrice;
	}

	public void setExPrice(Double exPrice) {
		this.exPrice = exPrice;
	}

	public Double getNoTax() {
		return noTax;
	}

	public void setNoTax(Double noTax) {
		this.noTax = noTax;
	}

	public Double getTax() {
		return tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	public Double getCostPrice() {
		return costPrice;
	}

	public void setCostPrice(Double costPrice) {
		this.costPrice = costPrice;
	}

	public Double getCostTax() {
		return costTax;
	}

	public void setCostTax(Double costTax) {
		this.costTax = costTax;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.ACCESSORIES
     *
     * @param accessories the value for ext_cproduct_c.ACCESSORIES
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setAccessories(Boolean accessories) {
        this.accessories = accessories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_cproduct_c.ORDER_NO
     *
     * @return the value of ext_cproduct_c.ORDER_NO
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_cproduct_c.ORDER_NO
     *
     * @param orderNo the value for ext_cproduct_c.ORDER_NO
     *
     * @mbggenerated Thu Jun 02 11:52:06 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}