package com.athome.ebusiness.domain;

import java.util.Date;

public class SysCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.SYS_CODE_ID
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.NAME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.PARENT_ID
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.PARENT_NAME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.LAYER_NUM
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private Integer layerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.IS_LEAF
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.ICO
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String ico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.STATE
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.CNOTE
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String cnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.QUOTE_NUM
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private Integer quoteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.ORDER_NO
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.CREATED_BY
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.CREATED_TIME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.UPDATED_BY
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_code_b.UPDATED_TIME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    private Date updatedTime;


    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.NAME
     *
     * @return the value of sys_code_b.NAME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.NAME
     *
     * @param name the value for sys_code_b.NAME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.PARENT_ID
     *
     * @return the value of sys_code_b.PARENT_ID
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.PARENT_ID
     *
     * @param parentId the value for sys_code_b.PARENT_ID
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.PARENT_NAME
     *
     * @return the value of sys_code_b.PARENT_NAME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.PARENT_NAME
     *
     * @param parentName the value for sys_code_b.PARENT_NAME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.LAYER_NUM
     *
     * @return the value of sys_code_b.LAYER_NUM
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public Integer getLayerNum() {
        return layerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.LAYER_NUM
     *
     * @param layerNum the value for sys_code_b.LAYER_NUM
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setLayerNum(Integer layerNum) {
        this.layerNum = layerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.IS_LEAF
     *
     * @return the value of sys_code_b.IS_LEAF
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.IS_LEAF
     *
     * @param isLeaf the value for sys_code_b.IS_LEAF
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.ICO
     *
     * @return the value of sys_code_b.ICO
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.ICO
     *
     * @param ico the value for sys_code_b.ICO
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setIco(String ico) {
        this.ico = ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.STATE
     *
     * @return the value of sys_code_b.STATE
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.STATE
     *
     * @param state the value for sys_code_b.STATE
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.CNOTE
     *
     * @return the value of sys_code_b.CNOTE
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getCnote() {
        return cnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.CNOTE
     *
     * @param cnote the value for sys_code_b.CNOTE
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setCnote(String cnote) {
        this.cnote = cnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.QUOTE_NUM
     *
     * @return the value of sys_code_b.QUOTE_NUM
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public Integer getQuoteNum() {
        return quoteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.QUOTE_NUM
     *
     * @param quoteNum the value for sys_code_b.QUOTE_NUM
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setQuoteNum(Integer quoteNum) {
        this.quoteNum = quoteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.ORDER_NO
     *
     * @return the value of sys_code_b.ORDER_NO
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.ORDER_NO
     *
     * @param orderNo the value for sys_code_b.ORDER_NO
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.CREATED_BY
     *
     * @return the value of sys_code_b.CREATED_BY
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.CREATED_BY
     *
     * @param createdBy the value for sys_code_b.CREATED_BY
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.CREATED_TIME
     *
     * @return the value of sys_code_b.CREATED_TIME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.CREATED_TIME
     *
     * @param createdTime the value for sys_code_b.CREATED_TIME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.UPDATED_BY
     *
     * @return the value of sys_code_b.UPDATED_BY
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.UPDATED_BY
     *
     * @param updatedBy the value for sys_code_b.UPDATED_BY
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_code_b.UPDATED_TIME
     *
     * @return the value of sys_code_b.UPDATED_TIME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_code_b.UPDATED_TIME
     *
     * @param updatedTime the value for sys_code_b.UPDATED_TIME
     *
     * @mbggenerated Fri Jun 03 11:40:05 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}